# Generated by Django 5.1.3 on 2024-12-04 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_canales', models.IntegerField()),
                ('horas_jornada', models.IntegerField()),
                ('canales_hora', models.IntegerField()),
                ('tiempo_entre_canales', models.IntegerField()),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.FloatField()),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corte')),
            ],
        ),
        migrations.CreateModel(
            name='Pausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_pausa', models.DateTimeField(auto_now_add=True)),
                ('fin_pausa', models.DateTimeField(blank=True, null=True)),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corte')),
            ],
        ),
    ]
