# Generated by Django 5.1.3 on 2024-12-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corte',
            name='grasa_carne',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corte',
            name='hueso_carne',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corte',
            name='tiempo_muerto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
