# Generated by Django 5.1.3 on 2024-12-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_corte_grasa_carne_corte_hueso_carne_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Grasa en carne', 'Grasa en carne'), ('Hueso en carne', 'Hueso en carne'), ('Piezas Vendibles', 'Piezas Vendibles')], max_length=50)),
                ('verde', models.CharField(max_length=50)),
                ('amarillo', models.CharField(max_length=50)),
                ('rojo', models.CharField(max_length=50)),
            ],
        ),
    ]
