# Generated by Django 5.1.3 on 2024-12-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='corte',
            name='piezas_vendibles',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
