# Generated by Django 5.1.3 on 2024-12-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_corte_piezas_vendibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='amarillo',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='rojo',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='verde',
            field=models.FloatField(max_length=50),
        ),
    ]
