# Generated by Django 5.1.4 on 2025-01-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_configuracion_amarillo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte',
            name='tiempo_entre_canales',
            field=models.FloatField(),
        ),
    ]
