# Generated by Django 5.1.3 on 2025-01-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_configuracion_amarillo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte',
            name='canales_hora',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='corte',
            name='horas_jornada',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='corte',
            name='tiempo_entre_canales',
            field=models.FloatField(),
        ),
    ]
