# Generated by Django 5.1.4 on 2025-01-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_corte_canales_hora_alter_corte_horas_jornada_and_more'),
        ('core', '0006_alter_corte_tiempo_entre_canales'),
    ]

    operations = [
    ]
